[package]
name = "deterministic_finite_automaton"
version = "0.1.0"
authors = ["Robert Węcławski <r.weclawski@gmail.com>"]

[dependencies]
itertools = "0.7.1"
serde_json = "1.0"
serde = "1.0.16"
serde_derive = "1.0.16"